//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta3

import (
	config "gitee.com/openeuler/paws/scheduler/apis/config"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*MetricProviderSpec)(nil), (*config.MetricProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_MetricProviderSpec_To_config_MetricProviderSpec(a.(*MetricProviderSpec), b.(*config.MetricProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.MetricProviderSpec)(nil), (*MetricProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_MetricProviderSpec_To_v1beta3_MetricProviderSpec(a.(*config.MetricProviderSpec), b.(*MetricProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TargetMetricSpec)(nil), (*config.TargetMetricSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_TargetMetricSpec_To_config_TargetMetricSpec(a.(*TargetMetricSpec), b.(*config.TargetMetricSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TargetMetricSpec)(nil), (*TargetMetricSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TargetMetricSpec_To_v1beta3_TargetMetricSpec(a.(*config.TargetMetricSpec), b.(*TargetMetricSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemporalUtilizationArgs)(nil), (*config.TemporalUtilizationArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(a.(*TemporalUtilizationArgs), b.(*config.TemporalUtilizationArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TemporalUtilizationArgs)(nil), (*TemporalUtilizationArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(a.(*config.TemporalUtilizationArgs), b.(*TemporalUtilizationArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta3_MetricProviderSpec_To_config_MetricProviderSpec(in *MetricProviderSpec, out *config.MetricProviderSpec, s conversion.Scope) error {
	out.Type = config.MetricProviderType(in.Type)
	if err := v1.Convert_Pointer_string_To_string(&in.Address, &out.Address, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.Token, &out.Token, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.InsecureSkipVerify, &out.InsecureSkipVerify, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta3_MetricProviderSpec_To_config_MetricProviderSpec is an autogenerated conversion function.
func Convert_v1beta3_MetricProviderSpec_To_config_MetricProviderSpec(in *MetricProviderSpec, out *config.MetricProviderSpec, s conversion.Scope) error {
	return autoConvert_v1beta3_MetricProviderSpec_To_config_MetricProviderSpec(in, out, s)
}

func autoConvert_config_MetricProviderSpec_To_v1beta3_MetricProviderSpec(in *config.MetricProviderSpec, out *MetricProviderSpec, s conversion.Scope) error {
	out.Type = MetricProviderType(in.Type)
	if err := v1.Convert_string_To_Pointer_string(&in.Address, &out.Address, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.Token, &out.Token, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.InsecureSkipVerify, &out.InsecureSkipVerify, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_MetricProviderSpec_To_v1beta3_MetricProviderSpec is an autogenerated conversion function.
func Convert_config_MetricProviderSpec_To_v1beta3_MetricProviderSpec(in *config.MetricProviderSpec, out *MetricProviderSpec, s conversion.Scope) error {
	return autoConvert_config_MetricProviderSpec_To_v1beta3_MetricProviderSpec(in, out, s)
}

func autoConvert_v1beta3_TargetMetricSpec_To_config_TargetMetricSpec(in *TargetMetricSpec, out *config.TargetMetricSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := v1.Convert_Pointer_string_To_string(&in.MetricLabel, &out.MetricLabel, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta3_TargetMetricSpec_To_config_TargetMetricSpec is an autogenerated conversion function.
func Convert_v1beta3_TargetMetricSpec_To_config_TargetMetricSpec(in *TargetMetricSpec, out *config.TargetMetricSpec, s conversion.Scope) error {
	return autoConvert_v1beta3_TargetMetricSpec_To_config_TargetMetricSpec(in, out, s)
}

func autoConvert_config_TargetMetricSpec_To_v1beta3_TargetMetricSpec(in *config.TargetMetricSpec, out *TargetMetricSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := v1.Convert_string_To_Pointer_string(&in.MetricLabel, &out.MetricLabel, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_TargetMetricSpec_To_v1beta3_TargetMetricSpec is an autogenerated conversion function.
func Convert_config_TargetMetricSpec_To_v1beta3_TargetMetricSpec(in *config.TargetMetricSpec, out *TargetMetricSpec, s conversion.Scope) error {
	return autoConvert_config_TargetMetricSpec_To_v1beta3_TargetMetricSpec(in, out, s)
}

func autoConvert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(in *TemporalUtilizationArgs, out *config.TemporalUtilizationArgs, s conversion.Scope) error {
	if err := v1.Convert_Pointer_int32_To_int32(&in.BestEffortPercentile, &out.BestEffortPercentile, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_int32_To_int32(&in.LatencyCriticalPercentile, &out.LatencyCriticalPercentile, s); err != nil {
		return err
	}
	if err := Convert_v1beta3_MetricProviderSpec_To_config_MetricProviderSpec(&in.MetricProvider, &out.MetricProvider, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.WatcherAddress, &out.WatcherAddress, s); err != nil {
		return err
	}
	if in.TargetMetrics != nil {
		in, out := &in.TargetMetrics, &out.TargetMetrics
		*out = make([]config.TargetMetricSpec, len(*in))
		for i := range *in {
			if err := Convert_v1beta3_TargetMetricSpec_To_config_TargetMetricSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.TargetMetrics = nil
	}
	if err := v1.Convert_Pointer_float64_To_float64(&in.HotSpotThreshold, &out.HotSpotThreshold, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs is an autogenerated conversion function.
func Convert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(in *TemporalUtilizationArgs, out *config.TemporalUtilizationArgs, s conversion.Scope) error {
	return autoConvert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(in, out, s)
}

func autoConvert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(in *config.TemporalUtilizationArgs, out *TemporalUtilizationArgs, s conversion.Scope) error {
	if err := v1.Convert_int32_To_Pointer_int32(&in.BestEffortPercentile, &out.BestEffortPercentile, s); err != nil {
		return err
	}
	if err := v1.Convert_int32_To_Pointer_int32(&in.LatencyCriticalPercentile, &out.LatencyCriticalPercentile, s); err != nil {
		return err
	}
	if err := Convert_config_MetricProviderSpec_To_v1beta3_MetricProviderSpec(&in.MetricProvider, &out.MetricProvider, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.WatcherAddress, &out.WatcherAddress, s); err != nil {
		return err
	}
	if in.TargetMetrics != nil {
		in, out := &in.TargetMetrics, &out.TargetMetrics
		*out = make([]TargetMetricSpec, len(*in))
		for i := range *in {
			if err := Convert_config_TargetMetricSpec_To_v1beta3_TargetMetricSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.TargetMetrics = nil
	}
	if err := v1.Convert_float64_To_Pointer_float64(&in.HotSpotThreshold, &out.HotSpotThreshold, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs is an autogenerated conversion function.
func Convert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(in *config.TemporalUtilizationArgs, out *TemporalUtilizationArgs, s conversion.Scope) error {
	return autoConvert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(in, out, s)
}
