//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta3

import (
	config "gitee.com/openeuler/paws/scheduler/apis/config"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*TemporalUtilizationArgs)(nil), (*config.TemporalUtilizationArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(a.(*TemporalUtilizationArgs), b.(*config.TemporalUtilizationArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TemporalUtilizationArgs)(nil), (*TemporalUtilizationArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(a.(*config.TemporalUtilizationArgs), b.(*TemporalUtilizationArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(in *TemporalUtilizationArgs, out *config.TemporalUtilizationArgs, s conversion.Scope) error {
	if err := v1.Convert_Pointer_int32_To_int32(&in.HotSpotThreshold, &out.HotSpotThreshold, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.HardThreshold, &out.HardThreshold, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.EnableOvercommit, &out.EnableOvercommit, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.FilterByTemporalUsages, &out.FilterByTemporalUsages, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs is an autogenerated conversion function.
func Convert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(in *TemporalUtilizationArgs, out *config.TemporalUtilizationArgs, s conversion.Scope) error {
	return autoConvert_v1beta3_TemporalUtilizationArgs_To_config_TemporalUtilizationArgs(in, out, s)
}

func autoConvert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(in *config.TemporalUtilizationArgs, out *TemporalUtilizationArgs, s conversion.Scope) error {
	if err := v1.Convert_int32_To_Pointer_int32(&in.HotSpotThreshold, &out.HotSpotThreshold, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.HardThreshold, &out.HardThreshold, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.EnableOvercommit, &out.EnableOvercommit, s); err != nil {
		return err
	}
	if err := v1.Convert_bool_To_Pointer_bool(&in.FilterByTemporalUsages, &out.FilterByTemporalUsages, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs is an autogenerated conversion function.
func Convert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(in *config.TemporalUtilizationArgs, out *TemporalUtilizationArgs, s conversion.Scope) error {
	return autoConvert_config_TemporalUtilizationArgs_To_v1beta3_TemporalUtilizationArgs(in, out, s)
}
