kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: predictive-core-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - serviceaccounts
  - events
  - configmaps
  - secrets
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  - verticalpodautoscalercheckpoints
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictive-core
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: predictive-core-role-binding
subjects:
- kind: ServiceAccount
  name: predictive-core
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: predictive-core-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-name
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommender-name
  template:
    metadata:
      labels:
        app: recommender-name
    spec:
      containers:
        - name: recommender-name
          image: docker.io/sneceesay77/paws:v1.0.0 # Replace this accordingly
          imagePullPolicy: Always
      serviceAccountName: predictive-core
      serviceAccount: predictive-core