apiVersion: v1
kind: Pod
metadata:
  name: curlbox-example
  namespace: default
  labels:
    app.kubernetes.io/part-of: curlbox-application-2
spec:
  schedulerName: paws-temporal
  containers:
  - name: curlbox
    image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    tty: true